Simplify unicorn init script
and add support for standard chef service actions

diff --git a/unicorn/templates/default/unicorn.init.erb b/unicorn/templates/default/unicorn.init.erb
--- a/unicorn/templates/default/unicorn.init.erb
+++ b/unicorn/templates/default/unicorn.init.erb
@@ -37,28 +37,14 @@ force-stop)
     sig TERM && exit 0
     echo >&2 "Not running"
     ;;
-restart|reload)
+reload)
     sig HUP && echo reloaded OK && exit 0
     echo >&2 "Couldn't reload, starting '$CMD' instead"
     $CMD
     ;;
-upgrade)
-    if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
-    then
-      n=$TIMEOUT
-      while test -s $old_pid && test $n -ge 0
-      do
-        printf '.' && sleep 1 && n=$(( $n - 1 ))
-      done
-      echo
-      if test $n -lt 0 && test -s $old_pid
-      then
-        echo >&2 "$old_pid still exists after $TIMEOUT seconds"
-        exit 1
-      fi
-      exit 0
-    fi
-    echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+restart)
+    sig USR2 && sleep 5 && oldsig QUIT && echo "Killing old master" `cat $OLD_PID` && exit 0
+    echo >&2 "Couldn't reload, starting '$CMD' instead"
     $CMD
     ;;
 reopen-logs)
