Change unicorn init script and add upgrade action

diff --git a/unicorn/templates/default/unicorn.init.erb b/unicorn/templates/default/unicorn.init.erb
--- a/unicorn/templates/default/unicorn.init.erb
+++ b/unicorn/templates/default/unicorn.init.erb
@@ -1,50 +1,75 @@
 #! /bin/sh
-
-### BEGIN INIT INFO
-# Provides:          unicorn
-# Required-Start:    $local_fs $remote_fs $network $syslog
-# Required-Stop:     $local_fs $remote_fs $network $syslog
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: starts the unicorn web server for <%= @application %>
-# Description:       starts unicorn for <%= @application %>
-### END INIT INFO
+set -e
 
 export SL_NAME=unicorn
-<% options = "#{@app_path}/shared/config/unicorn.rb -E #{@rails_env} -D" %>
-NAME=unicorn_<%= @application %>
-DESC=unicorn_<%= @application %>
+
+TIMEOUT=${TIMEOUT-60}
+APP_ROOT=<%= @current_path %>
 PID=<%= @app_path %>/shared/pids/unicorn_<%= @application %>.pid
+<% options = "#{@app_path}/shared/config/unicorn.rb -E #{@rails_env} -D" %>
+CMD="bundle exec unicorn -c <%= options %>"
+INIT_CONF=$APP_ROOT/config/init.conf
+action="$1"
+set -u
 
-cd <%= @current_path %>
+test -f "$INIT_CONF" && . $INIT_CONF
 
-case "$1" in
-  start)
-	echo -n "Starting $DESC: "
-  bundle exec unicorn -c <%= options %>
-	echo "$NAME."
-	;;
-  stop)
-	echo -n "Stopping $DESC: "
-        kill -QUIT `cat $PID`
-	echo "$NAME."
-	;;
-  restart)
-	echo -n "Restarting $DESC: "
-        kill -QUIT `cat $PID`
-	sleep 1
-  bundle exec unicorn -c <%= options %>
-	echo "$NAME."
-	;;
-  reload)
-        echo -n "Reloading $DESC configuration: "
-        kill -HUP `cat $PID`
-        echo "$NAME."
-        ;;
-  *)
-	echo "Usage: $NAME {start|stop|restart|reload}" >&2
-	exit 1
-	;;
+old_pid="$PID.oldbin"
+
+cd $APP_ROOT || exit 1
+
+sig () {
+	test -s "$PID" && kill -$1 `cat $PID`
+}
+
+oldsig () {
+	test -s $old_pid && kill -$1 `cat $old_pid`
+}
+
+
+case $action in
+start)
+    sig 0 && echo >&2 "Already running" && exit 0
+    $CMD
+    ;;
+stop)
+    sig QUIT && exit 0
+    echo >&2 "Not running"
+    ;;
+force-stop)
+    sig TERM && exit 0
+    echo >&2 "Not running"
+    ;;
+restart|reload)
+    sig HUP && echo reloaded OK && exit 0
+    echo >&2 "Couldn't reload, starting '$CMD' instead"
+    $CMD
+    ;;
+upgrade)
+    if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
+    then
+      n=$TIMEOUT
+      while test -s $old_pid && test $n -ge 0
+      do
+        printf '.' && sleep 1 && n=$(( $n - 1 ))
+      done
+      echo
+
+      if test $n -lt 0 && test -s $old_pid
+      then
+        echo >&2 "$old_pid still exists after $TIMEOUT seconds"
+        exit 1
+      fi
+      exit 0
+    fi
+    echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+    $CMD
+    ;;
+reopen-logs)
+    sig USR1
+    ;;
+*)
+    echo >&2 "Usage: $0 <start|stop|restart|upgrade|force-stop|reopen-logs>"
+    exit 1
+    ;;
 esac
-
-exit 0
